services:
  fastapi:
    environment:
      - TZ=Asia/Shanghai
    platform: linux/amd64
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    environment:
      - TZ=Asia/Shanghai
    platform: linux/amd64
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge

